variable "env" {
  type        = string
  description = "Deployment environment (dev, staging, prod)"
  validation {
    condition     = contains(["dev", "staging", "prod"], var.env)
    error_message = "env must be one of: dev, staging, prod"
  }
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Additional tags to merge onto all resources in this module"
}

variable "collections_table_arn" {
  type        = string
  description = "ARN of the DynamoDB collections table (from storage module)"
}

variable "images_table_arn" {
  type        = string
  description = "ARN of the DynamoDB images table (from storage module)"
}

variable "embed_model_id" {
  type        = string
  default     = "amazon.titan-embed-image-v1"
  description = "Bedrock model ID for text embedding (used to scope the InvokeModel IAM policy)"
}

variable "collections_table_name" {
  type        = string
  description = "Name of the DynamoDB collections table (from storage module)"
}

variable "images_table_name" {
  type        = string
  description = "Name of the DynamoDB images table (from storage module)"
}

variable "cognito_user_pool_id" {
  type        = string
  description = "Cognito User Pool ID injected into the API handler for token validation context"
}

variable "cognito_user_pool_arn" {
  type        = string
  description = "Cognito User Pool ARN used as the provider for the API Gateway authorizer"
}

variable "lambda_memory_mb" {
  type        = number
  default     = 512
  description = "Memory (MB) allocated to the API handler Lambda"
}

variable "lambda_timeout_seconds" {
  type        = number
  default     = 30
  description = "Timeout (seconds) for the API handler Lambda"
}

variable "log_retention_days" {
  type        = number
  default     = 30
  description = "CloudWatch log retention (days) for the API handler log group"
}

variable "presigned_url_ttl_seconds" {
  type        = number
  default     = 300
  description = "TTL (seconds) for S3 presigned URLs generated by the API handler"
}

variable "api_stage_name" {
  type = string
  # Stage name convention: the stage equals the environment name (dev, staging,
  # prod), so the invoke URL is
  #   https://{api-id}.execute-api.{region}.amazonaws.com/{env}/v1/{resource}
  # Only the host (api-id) varies per environment; the resource path (/v1/...)
  # is identical everywhere and no environment name is embedded in the resource
  # tree. An empty string here means "use var.env" (wired in main.tf via the
  # local below); it must NOT be "v1", which would collide with the /v1 resource
  # path prefix and cause requests to fall through to API Gateway's default
  # (IAM) handler — surfacing a misleading 403 IncompleteSignatureException.
  default     = ""
  description = "API Gateway stage name. Defaults to the environment name (var.env). Must not equal the API path version prefix (v1)."

  validation {
    condition     = var.api_stage_name != "v1"
    error_message = "api_stage_name must not be 'v1' — it collides with the /v1 resource path prefix. Leave it empty to use the environment name."
  }
}

variable "layer_arn" {
  type        = string
  description = "ARN of the shared dependencies Lambda layer (from the layer module)"
}

variable "api_gateway_rate_limit" {
  type        = number
  default     = 100
  description = "Steady-state requests per second for the API Gateway usage plan"
}

variable "api_gateway_burst_limit" {
  type        = number
  default     = 200
  description = "Maximum burst requests for the API Gateway usage plan"
}
