variable "env" {
  type        = string
  description = "Deployment environment (dev, staging, prod)"
  validation {
    condition     = contains(["dev", "staging", "prod"], var.env)
    error_message = "env must be one of: dev, staging, prod"
  }
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Additional tags to merge onto all resources in this module"
}

variable "collections_table_arn" {
  type        = string
  description = "ARN of the DynamoDB collections table (from storage module)"
}

variable "images_table_arn" {
  type        = string
  description = "ARN of the DynamoDB images table (from storage module)"
}

variable "embed_model_id" {
  type        = string
  default     = "amazon.titan-embed-image-v1"
  description = "Bedrock model ID for text embedding (used to scope the InvokeModel IAM policy)"
}

variable "collections_table_name" {
  type        = string
  description = "Name of the DynamoDB collections table (from storage module)"
}

variable "images_table_name" {
  type        = string
  description = "Name of the DynamoDB images table (from storage module)"
}

variable "cognito_user_pool_id" {
  type        = string
  description = "Cognito User Pool ID injected into the API handler for token validation context"
}

variable "cognito_user_pool_arn" {
  type        = string
  description = "Cognito User Pool ARN used as the provider for the API Gateway authorizer"
}

variable "lambda_memory_mb" {
  type        = number
  default     = 512
  description = "Memory (MB) allocated to the API handler Lambda"
}

variable "lambda_timeout_seconds" {
  type        = number
  default     = 30
  description = "Timeout (seconds) for the API handler Lambda"
}

variable "log_retention_days" {
  type        = number
  default     = 30
  description = "CloudWatch log retention (days) for the API handler log group"
}

variable "presigned_url_ttl_seconds" {
  type        = number
  default     = 300
  description = "TTL (seconds) for S3 presigned URLs generated by the API handler"
}

variable "api_stage_name" {
  type        = string
  default     = "v1"
  description = "API Gateway stage name"
}

variable "api_gateway_rate_limit" {
  type        = number
  default     = 100
  description = "Steady-state requests per second for the API Gateway usage plan"
}

variable "api_gateway_burst_limit" {
  type        = number
  default     = 200
  description = "Maximum burst requests for the API Gateway usage plan"
}
